name: lesionshiftai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - pytorch=2.4.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - numpy=2.3.4
  - pandas=2.3.3
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - albumentations
  - timm
  - pillow
  - pyyaml
  - tqdm
  - setuptools
  - wheel
  - pip
