name: lesionshiftai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.*
  - pytorch=2.4.*
  - torchvision=0.19.*
  - torchaudio=2.4.*
  - pytorch-cuda=12.1
  - numpy>=2,<3
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - timm
  - pillow
  - pyyaml
  - tqdm
  - jupyter
  - black
  - ruff
  - pytest
  - mypy
  - setuptools
  - wheel
  - pip
