name: lesionshiftai
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.2.*
  - torchvision=0.17.*
  - pytorch-cuda=12.1
  - numpy=1.26.*
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - albumentations
  - pillow
  - pyyaml
  - tqdm
  - jupyter
  - black
  - ruff
  - pytest
  - mypy
  - pip
  - pip:
      - timm
